name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y python3-gi
          fi
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile src/main.py --name userchrome-loader

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: userchrome-loader-${{ runner.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            userchrome-loader-Linux/*
            userchrome-loader-Windows/*
            userchrome-loader-macOS/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
